### ISSUE TITLE
Prikazovanje zemljevida

### ISSUE THREAD

**Issue by LeaHolc** [LeaHolc/APPR-2021-22#1]
Naletela sem na naslednjo težavo pri projektu:
Warning messages:
1: The projection of the shape object obcine.brezposelnost.zemljevid is not known, while it seems to be projected. 
2: Current projection of shape obcine.brezposelnost.zemljevid unknown and cannot be determined. 

Opozorilo se pojavi povsod, kjer imam zemljevide, tako pri analizi kot vizualizaciji.
Zemljevidi se mi sicer normalno prikazujejo in izrišejo ampak mi opozorilo onemogoča, da bi zemljevid prikazala v projekt.Rmd, ker ga ne najde za prikaz. Ali lahko zemljevid v poročilo vključim na drugačen način?
Hvala za pomoč.

**Comment by evadezelak** [comment]
V projekt.rmd lahko napišeš samo `mapa1`, ne uporabi print. Potem deluje. Če boš imela še vedno težave, ti svetujem, da zakomentiraš v `vizualizacija.r` vse vrstice, kjer graf oziroma zemljevid samo pokličeš, da se izriše. Tega načeloma ne pustimo v kodi, ko kličemo grafe v projektu.

**Comment by LeaHolc** [comment]
Najlepša hvala, sedaj vse deluje.
