### ISSUE TITLE
Oddaja projekta

### ISSUE THREAD

**Issue by LeaHolc** [LeaHolc/APPR-2021-22#2]
Projekt sem dokončala in ga želim oddati v ocenjevanje.

**Comment by M4rble** [comment]
Poročilo projekta se prevede brez težav, z oddajo projekta je vse v redu.
Projekt bo ocenjen v naslednjih dneh.

**Comment by katarinabrilej** [comment]
Meni se projekt ne prevede, napaka je naslednja:
```
Error: Can't transform a data frame with duplicate names.
```
Pojavi pa se pri tabeli `enake.obcine` v `vizualizacija.r`

**Comment by LeaHolc** [comment]
Pozdravljeni,
sem poskusila še enkrat zagnati projekt in se mi sicer prevede brez težav. Kljub vsemu sem poskusila narediti manipulacijo z imeni, če je bila mogoče težava v tem, da dvakrat iz različnih tabel kličem stolpec z istim imenom. Upam da sedaj deluje.

**Comment by katarinabrilej** [comment]
Meni se zdaj graf5 ne izriše, dobim naslednjo napako
```
Error: Faceting variables must have at least one value
```

**Comment by LeaHolc** [comment]
Pozdravljeni,
meni vse deluje normalno in iskreno nimam več idej v čem bi bila lahko težava. Ali imate vi kakšen nasvet ali idejo, ker sama niti ne vem kaj naj gledam glede na to, da mi niti warninga ne pokaže pri tej tabeli in grafu in graf se mi pri klicu normalno nariše in kasneje ga vidim v poročilu?
Razmišljala sem, da bi se težava mogoče lahko pojavila, ker sama uporabljam windows in da se morda zato kakšen encoding drugače obnaša.  Čudno se mi zdi, da mi je 5 dni nazaj, ko sem oddala demonstrator sporočil, da se vse prevaja normalno.
Hvala za pomoč in se opravičujem, ker je toliko težav.

**Comment by katarinabrilej** [comment]
Bom že nekako uredila, se Anžetu prevede. Je vse v redu s projektom:)

**Comment by LeaHolc** [comment]
Najlepša hvala za ves trud, me je že malo skrbelo kaj vse sem naredila narobe in kje so težave.

**Comment by katarinabrilej** [comment]
Ocena in komentar sta vpisana v spletni učilnici.
